services:
  # CRM Backend Service
  - type: web
    name: xeno-crm-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: '"Xeno CRM" <your-email@gmail.com>'
      - key: CHANNEL_SERVICE_URL
        sync: false

  # Simulated Channel Delivery Service
  - type: web
    name: xeno-channel-service
    env: node
    plan: free
    rootDir: channel-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: CRM_WEBHOOK_URL
        sync: false
